version: "3"
services: 
  frontend: 
    container_name: frontend 
    image: rishmitha/gcfe
    ports: 
     - "80:80"
    
  jobservice: 
    image: rishmitha/gcbe1
    ports: 
     - "5000:8082"
    depends_on: 
      - postgresql 
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgresql:
    image: rishmitha/postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    
  organizationservice: 
    image: rishmitha/orgservice1 
    ports: 
      - "5001:8081" 
    depends_on:
      - postgresql 
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
